### ISSUE TITLE
Highlight silkscreen mismatch info more

### ISSUE THREAD

**Issue by burkfers** [Bastardkb/bastardkb.github.io#11]
The cnano build guide mentions the silkscreen row label mismatch, but it's a simple info box without a highlight, hidden at the bottom of the section after two images.

http://docs.bastardkb.com/bg_cnano/09cables_to_splinky.html#left-side

This could be changed from a note to an info or even warning to make it less easy to miss.

**Comment by bstiq** [comment]
solved as of 9ddaee3. Thanks!

**Comment by burkfers** [comment]
The right side still has the old note at the bottom: http://docs.bastardkb.com/bg_cnano/09cables_to_splinky.html#right-side

**Comment by bstiq** [comment]
fixed
