### ISSUE TITLE
add keymap pictures to the docs

### ISSUE THREAD

**Issue by bstiq** [Bastardkb/bastardkb.github.io#17]
With #12 ~~almost~~ merged, 

- [x] place the pictures somewhere in the docs
- [ ] link to the pics from the qmk readme's
- [ ] remove old keymap pictures from qmk*
- [x] add dilemma / dilemma max pics

Keymap pictures to remove:
- https://github.com/Bastardkb/bastardkb-qmk/tree/bkb-master/keyboards/bastardkb/charybdis/4x6/keymaps/via#layout
- https://github.com/Bastardkb/bastardkb-qmk/tree/bkb-master/keyboards/bastardkb/charybdis/3x5/keymaps/via#layout

Optional:
- [ ] add layout pictures to the bastardkb.com product pages

About where to place the pictures - 
I'm open to discussion, but my initial ideas are in:
- "customizing your keyboard" section of each guide
- link to those pages in a new "keymaps" document in the firmware section

**Comment by burkfers** [comment]
`add dilemma / dilemma max pics` handled by #18

**Comment by bstiq** [comment]
handled by https://github.com/Bastardkb/bastardkb.github.io/issues/24
