### ISSUE TITLE
Document the charybdis trackball side needing the usb-c connection

### ISSUE THREAD

**Issue by razzeee** [Bastardkb/bastardkb.github.io#34]
I'm not sure, if it's correct, but it seems to be the case for me (might be weirds TRRS cable)

But if it's true, that the half with the trackball needs to be connected via usb-c, we should probably mention it somewhere in the docs?

I would have expected that here https://docs.bastardkb.com/bg_charybdis/13customize.html as that's where you finished the build and try as a whole for the first time.

**Comment by burkfers** [comment]
The [testing](https://docs.bastardkb.com/bg_charybdis/10install_the_switches.html#testing-the-switches) part mentions that usb canonically goes on the right (on all build guides), but you're right, this could be made more explicit on other pages, such as the one you suggest.

CC @bstiq

**Comment by bstiq** [comment]
Good point.

This should be enough? https://bstiq.github.io/bstiqbstkbd.github.io/bg_charybdis/13customize.html#introduction

![image](https://github.com/user-attachments/assets/ce5ca7fd-b148-4222-8c02-82001e796c07)

**Comment by razzeee** [comment]
> The [testing](https://docs.bastardkb.com/bg_charybdis/10install_the_switches.html#testing-the-switches) part mentions that usb canonically goes on the right (on all build guides), but you're right, this could be made more explicit on other pages, such as the one you suggest.

I think I even read that and mainly remembered about it, that I shouldn't be surprised, if the keyboard shows up as the same half. (which it did for me on linux without the udev rule)

I think that `note` would improve the docs

**Comment by bstiq** [comment]
Done. Thanks!
