### ISSUE TITLE
required tools: specify screwdriver sizes

### ISSUE THREAD

**Issue by burkfers** [Bastardkb/bastardkb.github.io#5]
The required screwdrivers should be specified as TXnn, such as TX10 for the larger screws used in the Dilemma. The given M3/M4 sizes refer to the thread and only relate to the driver interface indirectly.

**Comment by bstiq** [comment]
Done, thanks !

**Comment by burkfers** [comment]
Thanks!

We should also change the generic required tools page.

The sizes are TX10 and TX20 for the M3 and M4 screws.

The Dactyl family only uses TX20. The Charybdis family uses TX20 for the case and TX10 for the sensor assembly.

**Comment by bstiq** [comment]
done, thanks
